# Generated by Django 4.1.5 on 2023-01-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether the user is verified and can log into his/her account.', verbose_name='staff status'),
        ),
    ]
