# Generated by Django 4.1.5 on 2023-01-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_backend', '0002_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether the user is verified and can log into his/her account.', verbose_name='Verified Status'),
        ),
    ]
