# Generated by Django 4.1.5 on 2023-01-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_backend', '0003_alter_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Proxy', 'Proxy'), ('Principal', 'Principal')], default='', max_length=50),
        ),
    ]
